"""Trip Orders - local web server.

Runs with the Python standard library only (no pip install needed).
Installed with TripOrders-Setup.exe (portable: start.bat); every PC on the network can then open the address
printed in the console window. Everybody must log in; what each user may see and
do is set by the administrator (Users page) and checked here for every request.
"""
import hashlib
import html
import re
import json
import logging
import logging.handlers
import mimetypes
import os
import socket
import sys
import threading
import time
import traceback
import uuid
import webbrowser
from datetime import datetime
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import parse_qs, unquote, urlparse

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)  # the portable (embedded) Python does not add the script folder itself

import backup as backup_mod  # noqa: E402
import xlsx  # noqa: E402
from auth import ADMIN_PERMS, ALL, PERMISSIONS, AuthError, Forbidden  # noqa: E402
import excel_io  # noqa: E402
import word_io  # noqa: E402
import reports  # noqa: E402
import tripsvc  # noqa: E402
from store import BadRequest, Conflict, now  # noqa: E402
from sync import SyncService  # noqa: E402
from system import System, lock_data  # noqa: E402

ROOT = os.path.dirname(HERE)  # program files (web pages); in the installed program they are built into TripOrders.exe (_assets)
HOME = os.environ.get('TO_HOME') or ROOT  # config.json, data and backups: %ProgramData%\TripOrders when installed
CONFIG_PATH = os.environ.get('TO_CONFIG') or os.path.join(HOME, 'config.json')
try:
    from _assets import ASSETS  # noqa: E402 - generated by tools/make_assets.py for the installed program
except ImportError:
    ASSETS = None
from version import COPYRIGHT, DEVELOPER, LICENSE_NOTE, PRODUCT, VERSION  # noqa: E402
DEFAULT_CONFIG = {
    'port': 8090,
    'host': '0.0.0.0',
    'data_dir': 'data',
    'backup_dir': 'backups',
    'extra_backup_dirs': [],
    'backup_interval_hours': 6,
    'keep_auto_backups': 200,
    'max_upload_mb': 50,
    'open_browser': True,
    'session_idle_minutes': 30,
    'session_max_hours': 12,
    'max_failed_logins': 5,
    'lockout_minutes': 15,
    'min_password_length': 8,
    'device_name': '',
    'sync_port': 8453,
    'sync_interval_seconds': 5,
    'peer_addresses': {},
}
STATIC = {'/': 'index.html', '/index.html': 'index.html'}
STATIC_DIRS = ('/css/', '/js/', '/lib/', '/fonts/')
STATIC_EXT = {'.html', '.js', '.css', '.svg', '.png', '.ico', '.woff', '.woff2', '.map', '.json'}
UPLOAD_EXT = {'.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp', '.heic', '.pdf', '.doc', '.docx', '.xls', '.xlsx',
              '.ppt', '.pptx', '.txt', '.csv', '.zip'}
IMAGE_EXT = {'.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp', '.heic'}
INLINE_EXT = {'.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp', '.pdf'}
TYPES = {'.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.html': 'text/html; charset=utf-8',
         '.json': 'application/json', '.svg': 'image/svg+xml', '.webp': 'image/webp', '.heic': 'image/heic',
         '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
         '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}


def load_config():
    cfg = dict(DEFAULT_CONFIG)
    if os.path.exists(CONFIG_PATH):
        with open(CONFIG_PATH, encoding='utf-8') as f:
            cfg.update(json.load(f))
    else:
        with open(CONFIG_PATH, 'w', encoding='utf-8') as f:
            json.dump(cfg, f, indent=2)
    return cfg


def set_backup_folder(folder):
    """Choose (or with '' remove) the second backup folder of this PC. Stored in config.json of this PC only."""
    if folder:
        folder = os.path.normpath(folder)
        if backup_mod.network_folder(folder):
            raise BadRequest('Choose a USB drive or another disk of this PC, not a network folder (the backups contain the passwords).')
        if not os.path.isabs(folder):
            raise BadRequest('Type the full folder, for example E:\\TO-Backups.')
        inside = [os.path.normcase(os.path.realpath(d)) for d in (HOME, DATA_DIR, BACKUPS.dir)]
        f = os.path.normcase(os.path.realpath(folder))
        if any(f == d or f.startswith(d + os.sep) for d in inside):
            raise BadRequest('Choose a folder on another disk or a USB drive, not inside the program data.')
        try:
            os.makedirs(folder, exist_ok=True)
            test = os.path.join(folder, '.to-write-test')
            with open(test, 'w') as fh:
                fh.write('ok')
            os.remove(test)
        except OSError:
            raise BadRequest('This folder cannot be used (not found or no permission to write). Check the drive and try again.')
    dirs = ([folder] if folder else []) + [d for d in CFG.get('extra_backup_dirs', [])[1:] if d]  # the screen sets the first one
    try:
        cfg = {}
        if os.path.exists(CONFIG_PATH):
            with open(CONFIG_PATH, encoding='utf-8') as fh:
                cfg = json.load(fh)
        cfg['extra_backup_dirs'] = dirs
        tmp = CONFIG_PATH + '.tmp'
        with open(tmp, 'w', encoding='utf-8') as fh:
            json.dump(cfg, fh, indent=2)
        os.replace(tmp, CONFIG_PATH)
    except (OSError, ValueError):
        raise BadRequest('The setting could not be saved (config.json is damaged or cannot be written).')
    CFG['extra_backup_dirs'] = dirs
    BACKUPS.extra = [resolve(d) for d in dirs]
    BACKUPS.last_error = ''


def resolve(p):
    return p if os.path.isabs(p) else os.path.join(HOME, p)


CFG = load_config()
DATA_DIR = resolve(CFG['data_dir'])
UPLOADS = os.path.join(DATA_DIR, 'uploads')
os.makedirs(UPLOADS, exist_ok=True)
os.makedirs(os.path.join(DATA_DIR, 'logs'), exist_ok=True)

log = logging.getLogger('triporders')
log.setLevel(logging.INFO)
_fh = logging.handlers.RotatingFileHandler(os.path.join(DATA_DIR, 'logs', 'server.log'), maxBytes=5 * 1048576, backupCount=20, encoding='utf-8')
_fh.setFormatter(logging.Formatter('%(asctime)s %(levelname)s %(message)s'))
log.addHandler(_fh)


def say(msg):
    log.info(msg)
    print(f'[{datetime.now():%H:%M:%S}] {msg}', flush=True)


INSTANCE = lock_data(DATA_DIR)  # taken before anything touches the data
if INSTANCE:
    SYSTEM = System(DATA_DIR, CFG, UPLOADS, resolve(CFG['backup_dir']), [resolve(d) for d in CFG['extra_backup_dirs']], log=say)
    STORE, AUTH, BACKUPS, JOURNAL, NODE = SYSTEM.store, SYSTEM.auth, SYSTEM.backups, SYSTEM.journal, SYSTEM.node
    SYNC = SyncService(SYSTEM, CFG, UPLOADS, log=say)
else:
    SYSTEM = STORE = AUTH = BACKUPS = JOURNAL = NODE = SYNC = None
PLACEHOLDER = (b'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 200"><rect width="320" height="200" fill="#eef1f5"/>'
               b'<text x="160" y="96" font-family="Segoe UI,Arial" font-size="15" text-anchor="middle" fill="#6b7785">Photo is being copied</text>'
               b'<text x="160" y="118" font-family="Segoe UI,Arial" font-size="12" text-anchor="middle" fill="#8a95a3">from another PC\u2026</text></svg>')
COOKIE = 'to_sid'
ABOUT = {'product': PRODUCT, 'version': VERSION, 'developer': DEVELOPER, 'copyright': COPYRIGHT, 'license': LICENSE_NOTE,
         'installed': ASSETS is not None}
LOCAL_IPS = ('127.0.0.1', '::1', '::ffff:127.0.0.1')
CSP = ("default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; "
       "connect-src 'self' data: blob:; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'")
PERM_LABEL = {p: label for _, ps in PERMISSIONS for p, label in ps}
REPORT_PERMS = [p for p in ALL if p.startswith('report.')] + ['excel.export', 'logs.view', 'logs.activity', 'logs.security']
ENTITY_TITLE = {'tripCategories': 'trip categories', 'vehicles': 'vehicles', 'drivers': 'drivers', 'departments': 'departments',
                'people': 'people', 'places': 'places', 'routes': 'standard routes', 'trips': 'trips',
                'tripPassengers': 'trip passengers', 'tripPhotos': 'trip photos', 'tripAmendments': 'trip amendments',
                'tripEvents': 'driver submissions', 'settings': 'settings'}
OP_WORD = {'insert': 'add', 'update': 'change', 'delete': 'delete'}
SHARED_LISTS = ('settings', 'vehicles', 'drivers', 'departments', 'people', 'places', 'routes')  # not limited to a category
GA_FIELDS = {'gaApproved', 'gaBy', 'gaAt'}
LINK_FIELDS = {'linkHash', 'linkNonce', 'linkExpiry', 'status', 'boundDevice'}
SYSTEM_ONLY = ('data.import',)  # driver submissions and amendments are written by the server itself, never by hand


def required(entity, op, changed):
    """The permissions (any one of them is enough) needed for one saved change."""
    if entity == 'trips':
        if op == 'insert':
            return ('trips.create', 'excel.import')
        if op == 'delete':
            return ('trips.delete',)
        keys = set(changed)
        if keys and keys <= GA_FIELDS:
            return ('trips.approve', 'trips.edit')
        if keys and keys <= LINK_FIELDS:
            return ('trips.send', 'trips.cancel', 'trips.review', 'trips.edit', 'trips.amend')
        return ('trips.edit', 'trips.amend', 'trips.review')
    return {
        'tripCategories': {'insert': ('categories.manage',), 'update': ('categories.manage',), 'delete': ('categories.manage',)},
        'vehicles': {'insert': ('vehicles.manage',), 'update': ('vehicles.manage',), 'delete': ('vehicles.manage',)},
        'drivers': {'insert': ('drivers.manage',), 'update': ('drivers.manage',), 'delete': ('drivers.manage',)},
        'departments': {'insert': ('people.manage',), 'update': ('people.manage',), 'delete': ('people.manage',)},
        'people': {'insert': ('people.manage', 'trips.create', 'excel.import'), 'update': ('people.manage',), 'delete': ('people.manage',)},
        'places': {'insert': ('places.manage', 'trips.create', 'excel.import'), 'update': ('places.manage',), 'delete': ('places.manage',)},
        'routes': {'insert': ('places.manage',), 'update': ('places.manage',), 'delete': ('places.manage',)},
        'tripPassengers': {'insert': ('trips.create', 'trips.edit', 'excel.import'), 'update': ('trips.edit',), 'delete': ('trips.edit', 'trips.delete')},
        'tripPhotos': {'insert': ('trips.edit', 'trips.review', 'trips.amend'), 'update': ('trips.edit', 'trips.review', 'trips.amend'), 'delete': ('files.delete',)},
        'tripAmendments': {'insert': ('trips.amend', 'trips.review'), 'update': SYSTEM_ONLY, 'delete': SYSTEM_ONLY},
        'tripEvents': {'insert': SYSTEM_ONLY, 'update': SYSTEM_ONLY, 'delete': SYSTEM_ONLY},
        'settings': {'insert': ('settings.edit',), 'update': ('settings.edit',), 'delete': ('settings.edit',)},
    }[entity][op]


def commit_guard(u):
    """Checks every change of a save against the user's permissions and trip categories."""
    perms, scope = set(u['perms']), (None if u['scopes'] is None else set(u['scopes']))

    def guard(changes, force):
        if force:  # replaces everything: import, load sample data, delete all sample data
            if 'data.import' not in perms or scope is not None:
                raise Forbidden('Only a user with the permission "' + PERM_LABEL['data.import'] + '" for all categories can replace all data.')
            return
        for c in changes:
            e, op, sc = c['entity'], c['op'], c['scope']
            if scope is not None and e not in SHARED_LISTS and not {sc, c.get('scope_before', sc)} <= scope:
                raise Forbidden('You are limited to certain trip categories and cannot add new ones.' if e == 'tripCategories' and op == 'insert'
                                else 'You can only change the trip categories assigned to you.')
            if e == 'trips' and op == 'update' and (c.get('before') or {}).get('locked') and not perms.intersection(('trips.amend', 'trips.review')):
                raise Forbidden('This trip is locked. A change needs the permission "' + PERM_LABEL['trips.amend'] + '" and a written reason.')
            need = required(e, op, c['changes'])
            if not perms.intersection(need):
                raise Forbidden(f'You are not allowed to {OP_WORD[op]} {ENTITY_TITLE[e]}. Ask the administrator for the permission "{PERM_LABEL[need[0]]}".')
    return guard


def lan_urls(port):
    urls = [f'http://{socket.gethostname()}:{port}/']
    try:
        for ip in socket.gethostbyname_ex(socket.gethostname())[2]:
            if not ip.startswith('127.'):
                urls.append(f'http://{ip}:{port}/')
    except OSError:
        pass
    return urls


def site_names():
    """System name and short name for the login screen (shown before anybody is logged in)."""
    out = {}
    try:
        with STORE.lock:
            for k, v in STORE.conn.execute("SELECT id, value FROM settings WHERE id IN ('systemName', 'logoText', 'factory')"):
                try:
                    v = json.loads(v)
                except (TypeError, ValueError):
                    pass
                if isinstance(v, str) and v.strip():
                    out[k] = v.strip()[:80]
    except Exception:  # noqa: BLE001 - only cosmetics for the login screen
        pass
    return out


class NotLoggedIn(Exception):
    pass


def is_admin(u):
    """Administrator = may manage users. Monitoring, devices and conflicts need this, checked on every request."""
    return bool(u) and 'users.manage' in u['perms']


FAILED = {}  # ip -> times of recent failed logins (this PC only)
FAILED_LOCK = threading.Lock()


def too_many_failures(ip, add=False):
    """More than 10 failed logins (password or link) from one address within a minute: refuse quickly for a while,
    without the slow password check and without filling the logs of every PC."""
    t = time.time()
    with FAILED_LOCK:
        recent = [x for x in FAILED.get(ip, []) if t - x < 60]
        if add:
            recent.append(t)
        if recent:
            FAILED[ip] = recent[-50:]
        else:
            FAILED.pop(ip, None)
        if len(FAILED) > 5000:  # never grow without limit
            FAILED.clear()
        return len(recent) > 10


class Handler(BaseHTTPRequestHandler):
    server_version = 'TripOrders/1.0'
    protocol_version = 'HTTP/1.1'
    timeout = 120  # a connection that stays silent is closed
    u = None  # the logged-in user of this request (set by login_required)
    _read = False  # True once the request body was read

    # ------------------------------------------------------------ plumbing
    def log_message(self, fmt, *args):
        pass  # API calls are logged explicitly below; static files are not worth logging

    @property
    def user(self):
        return self.u['display'] if self.u else 'Not logged in'

    @property
    def log_path(self):
        """The address for logs: the secret part of a personal link is never written anywhere."""
        return '/k/…' if self.path.startswith('/k/') else self.path

    @property
    def ip(self):
        return self.client_address[0]

    @property
    def token(self):
        for part in (self.headers.get('Cookie') or '').split(';'):
            k, _, v = part.strip().partition('=')
            if k == COOKIE:
                return v
        return ''

    def login_required(self, touch=True):
        self.u = AUTH.session(self.token, self.ip, touch)
        if not self.u:
            raise NotLoggedIn()
        return self.u

    def can(self, *perms):
        return bool(self.u) and any(p in self.u['perms'] for p in perms)

    def need(self, *perms):
        if not self.can(*perms):
            raise Forbidden('You do not have permission for this. Ask the administrator for: "' + PERM_LABEL[perms[0]] + '".')

    def send(self, code, body=b'', ctype='application/json', headers=None):
        if isinstance(body, (dict, list)):
            body = json.dumps(body, ensure_ascii=False).encode('utf-8')
        elif isinstance(body, str):
            body = body.encode('utf-8')
        self.send_response(code)
        unread = self.command == 'POST' and not self._read and int(self.headers.get('Content-Length') or 0)
        if code >= 400 or unread:  # the request body may be unread - don't reuse this connection
            self.close_connection = True
            self.send_header('Connection', 'close')
        self.send_header('Content-Type', ctype)
        self.send_header('Content-Length', str(len(body)))
        self.send_header('X-Content-Type-Options', 'nosniff')
        self.send_header('X-Frame-Options', 'DENY')
        self.send_header('Referrer-Policy', 'same-origin')
        if ctype.startswith('text/html'):
            self.send_header('Content-Security-Policy', CSP)
        headers = dict(headers or {})
        if self.path.startswith('/api/'):
            headers.setdefault('Cache-Control', 'no-store')
        for k, v in headers.items():
            self.send_header(k, v)
        self.end_headers()
        if self.command != 'HEAD':
            self.wfile.write(body)

    def link_page(self, token):
        """Opening a personal link shows a tiny page that logs in by itself (js/quick.js). Logging in only happens with the
        POST from this page, so a program that merely looks at the link (a chat preview, a virus scanner) logs nobody in."""
        u = AUTH.link_user(token)
        ok = u and u['active'] and AUTH.link_allowed(u)
        title = PRODUCT
        now_in = AUTH.session(self.token, self.ip, touch=False) if ok and self.token else None
        if now_in and now_in['id'] == u['id']:
            return self.send(303, b'', 'text/plain', {'Location': '/'})  # already logged in as this person
        if ok:
            form = (f'<form id="{"ask" if now_in else "go"}" method="post" action="/k/{html.escape(token)}">'
                    f'<button type="submit">{"Continue as " + html.escape(u["full_name"]) if now_in else "Open the system"}</button></form>')
            if now_in:  # somebody else is logged in in this browser: never switch without asking
                body = (f'<h1>Personal link of {html.escape(u["full_name"])}</h1><p>This browser is logged in as '
                        f'<b>{html.escape(now_in["full_name"])}</b>. Continuing logs {html.escape(now_in["full_name"])} out.</p>' + form +
                        '<p class="small"><a href="/">Stay as ' + html.escape(now_in['full_name']) + '</a></p>')
            else:
                body = (f'<h1>Welcome, {html.escape(u["full_name"])}</h1><p>Opening the system for you…</p>' + form +
                        '<p class="small">This is your personal link. Do not give it to anybody - whoever has it works under your name.</p>'
                        '<script src="/js/quick.js"></script>')
        else:
            body = ('<h1>This link does not work any more</h1><p>Please ask the administrator for your new link, '
                    'or <a href="/">log in with your user name and password</a>.</p>')
        page = (f'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
                f'<title>{html.escape(title)}</title><style>body{{font-family:system-ui,Segoe UI,Arial,'
                'sans-serif;background:#f3f5f8;color:#1b2533;display:flex;min-height:90vh;align-items:center;justify-content:center;margin:0 16px}'
                'main{background:#fff;border-radius:12px;padding:28px 32px;max-width:440px;box-shadow:0 4px 18px #0001;text-align:center}'
                'h1{font-size:1.35rem}button{font-size:1.05rem;padding:10px 26px;border:0;border-radius:8px;background:#1f6feb;color:#fff;cursor:pointer}'
                '.small{font-size:.85rem;color:#5b6675;margin-top:18px}</style></head><body><main>' + body + '</main></body></html>')
        return self.send(200 if ok else 404, page, 'text/html; charset=utf-8', {'Cache-Control': 'no-store'})

    def set_session(self, token):
        return {'Set-Cookie': f'{COOKIE}={token}; Path=/; HttpOnly; SameSite=Strict'}

    def clear_session(self):
        return {'Set-Cookie': f'{COOKIE}=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0'}

    def body(self, limit=20 * 1048576):
        raw = self.headers.get('Content-Length') or '0'
        if not raw.isdigit():
            raise BadRequest('Invalid request length')
        n = int(raw)
        if n > limit:
            raise BadRequest(f'Request too large ({n // 1048576} MB)')
        self._read = True
        return self.rfile.read(n) if n else b''

    def json_body(self):
        raw = self.body(200 * 1048576 if self.u else 65536)  # before logging in only small requests
        return json.loads(raw.decode('utf-8')) if raw else {}

    def denied(self, msg):
        AUTH.log(self.user, self.ip, 'access-denied', self.log_path.split('?')[0], msg)
        try:
            STORE.log_activity(self.user, self.ip, [{'type': 'denied', 'action': self.log_path.split('?')[0], 'detail': msg}])
        except Exception:
            pass

    def handle_safely(self, fn):
        try:
            fn()
        except NotLoggedIn:
            self.send(401, {'error': 'Please log in.', 'login': True}, headers=self.clear_session())
        except Forbidden as e:
            log.info('DENIED %s %s %s', self.user, self.log_path, e)
            self.denied(str(e))
            self.send(403, {'error': str(e)})
        except AuthError as e:
            self.send(400, {'error': str(e)})
        except Conflict as e:
            log.info('CONFLICT %s %s %s', self.user, self.log_path, e)
            self.send(409, {'error': str(e)})
        except (BadRequest, ValueError) as e:
            log.info('BAD REQUEST %s %s %s', self.user, self.log_path, e)
            self.send(400, {'error': str(e)})
        except (ConnectionError, BrokenPipeError):
            pass
        except Exception as e:
            tb = traceback.format_exc()
            log.error('ERROR %s %s\n%s', self.user, self.log_path, tb)
            try:
                STORE.log_activity(self.user, self.ip, [{'type': 'server-error', 'action': self.log_path, 'detail': tb[-1900:]}])
            except Exception:
                pass
            self.send(500, {'error': f'Server error: {e}'})

    # ------------------------------------------------------------ routing
    def do_HEAD(self):
        self.do_GET()

    def do_GET(self):
        self.u = None
        self.handle_safely(self._get)

    def do_POST(self):
        self.u, self._read = None, False
        self.handle_safely(self._post)

    def me(self):
        u = self.u
        return {**AUTH.public(u), 'display': u['display'], 'permissions': PERMISSIONS, 'adminPerms': sorted(ADMIN_PERMS),
                'sessionIdleMinutes': CFG['session_idle_minutes'], 'minPasswordLength': AUTH.min_len, 'admin': is_admin(u), 'viaLink': bool(u.get('via_link')),
                'node': {'id': NODE.id, 'name': NODE.name, 'role': NODE.role, 'authority': NODE.is_authority}}

    def need_all_scopes(self):
        if self.u['scopes'] is not None:
            raise Forbidden('This shows all trip categories. It is only for users who work with all categories.')

    def need_admin(self):
        if not is_admin(self.u):
            raise Forbidden('Only an administrator can open this.')

    def node_status(self):
        j = JOURNAL.meta('join')
        return {'role': NODE.role, 'name': NODE.name, 'id': NODE.id, 'moved': NODE.moved,
                'join': {'confirm': j['confirm'], 'authority': j.get('authority')} if j and NODE.role == 'unconfigured' else None}

    def _get(self):
        url = urlparse(self.path)
        p, qs = url.path, {k: v[0] for k, v in parse_qs(url.query).items()}
        if p in STATIC:
            return self.serve_static(STATIC[p])
        if p.startswith(STATIC_DIRS):
            return self.serve_static(p.lstrip('/'))
        if p.startswith('/k/'):
            return self.link_page(p[3:])
        if p == '/api/auth/status':
            u = AUTH.session(self.token, self.ip, touch=False)
            self.u = u
            return self.send(200, {'hasUsers': AUTH.has_users(), 'local': self.ip in LOCAL_IPS, 'me': self.me() if u else None,
                                   'node': self.node_status(), 'about': {**ABOUT, **site_names()}})
        if p == '/api/join/status':
            if self.ip not in LOCAL_IPS or AUTH.has_users() and NODE.role != 'member':
                raise Forbidden('Only on this PC itself.')
            return self.send(200, {**SYNC.join_progress(), 'hasUsers': AUTH.has_users()})

        self.login_required(touch=p != '/api/version')
        if p == '/api/me':
            return self.send(200, self.me())
        if p == '/api/state':
            return self.send(200, STORE.state(self.u['scopes']))
        if p in ('/api/excel/export', '/api/excel/template'):
            self.need('excel.export')
            self.need_all_scopes()
            ym = qs.get('ym', '')
            if p.endswith('template'):
                data, name = excel_io.template(), 'Trips_template.xlsx'
            else:
                if not re.fullmatch(r'\d{4}-(0[1-9]|1[0-2])', ym):
                    raise BadRequest('Choose the month to export.')
                st = STORE.state(self.u['scopes'])
                data = excel_io.export_today(st, ym) if qs.get('layout', 'today') == 'today' else excel_io.export_clean(st, ym, qs.get('lang', 'en'))
                name = f'Trips_{ym}_{"clean" if qs.get("layout") == "clean" else "same-as-today"}.xlsx'
            STORE.log_activity(self.user, self.ip, [{'type': 'export', 'action': 'Excel export', 'target': name}])
            return self.send(200, data, TYPES['.xlsx'], {'Content-Disposition': f'attachment; filename="{name}"'})
        if p in ('/api/word/form', '/api/word/report'):
            st = STORE.state(self.u['scopes'])
            lang = 'ar' if qs.get('lang') == 'ar' else 'en'
            cfg = {x.get('id'): x.get('value') for x in st.get('settings', []) if isinstance(x, dict)}
            brand = {'name': cfg.get('systemName') or '', 'footer': cfg.get('formFooter') or ''}
            if p.endswith('report'):
                self.need('excel.export')
                self.need_all_scopes()
                ym = qs.get('ym', '')
                if ym and not re.fullmatch(r'\d{4}-(0[1-9]|1[0-2])', ym):
                    raise BadRequest('Choose the month.')
                data, name = word_io.report(st, ym, lang, brand), f'Trips_report_{ym or "all"}.docx'
            else:
                self.need('trips.view')
                ctx, name = {}, 'Trip_order_blank.docx'
                t = next((x for x in st.get('trips', []) if x['id'] == qs.get('trip')), None) if qs.get('trip') else None
                if t:
                    n = reports._names(st)
                    ctx = {'no': t.get('no', ''), 'passenger': (n['ppl'].get(t.get('requesterId')) or {}).get('name', ''), 'department': (n['dep'].get(t.get('departmentId')) or {}).get('name', ''),
                           'driver': (n['drv'].get(t.get('driverId')) or {}).get('name', ''), 'plate': (n['veh'].get(t.get('vehicleId')) or {}).get('plate', ''),
                           'carType': (n['cat'].get(t.get('categoryId')) or {}).get('name', ''), 'startDate': t.get('date', ''), 'route': t.get('destination', '')}
                    name = f'Trip_order_{t.get("no") or "draft"}.docx'
                data = word_io.form(ctx, lang, brand, cfg.get('legalText') or '')
            STORE.log_activity(self.user, self.ip, [{'type': 'export', 'action': 'Word export', 'target': name}])
            return self.send(200, data, TYPES['.docx'], {'Content-Disposition': f'attachment; filename="{name}"'})
        if p == '/api/insights':
            self.need('trips.view')
            return self.send(200, tripsvc.insights(STORE.state(self.u['scopes'])))
        if p == '/api/version':
            return self.send(200, {'version': STORE.version(), 'me': self.u['ver'], 'mustChange': bool(self.u['must_change']),
                                   'sync': SYNC.summary()})
        if p == '/api/info':
            urls = lan_urls(CFG['port'])
            if not self.can('settings.view'):
                return self.send(200, {'urls': urls})
            db_size = sum(os.path.getsize(os.path.join(DATA_DIR, f)) for f in os.listdir(DATA_DIR) if f.startswith('trips.db'))
            up_size = sum(os.path.getsize(os.path.join(r, f)) for r, _, fs in os.walk(UPLOADS) for f in fs)
            return self.send(200, {'urls': urls, 'dataDir': DATA_DIR, 'backupDir': BACKUPS.dir,
                                   'extraBackupDirs': BACKUPS.extra, 'dbSize': db_size, 'uploadsSize': up_size,
                                   'backupIntervalHours': CFG['backup_interval_hours'], 'lastBackupError': BACKUPS.last_error,
                                   'counts': STORE.counts(), 'serverTime': now()})
        if p == '/api/backups':
            self.need('backups.manage', 'backups.restore')
            return self.send(200, BACKUPS.list())
        if p == '/api/backups/folder':
            self.need('backups.manage')
            return self.send(200, {'dirs': BACKUPS.extra, 'error': BACKUPS.last_error, 'local': self.ip in LOCAL_IPS,
                                   'admin': is_admin(self.u)})
        if p == '/api/trash':
            self.need('trash.restore')
            self.need_all_scopes()
            return self.send(200, STORE.trash())
        if p in ('/api/audit', '/api/activity'):
            self.need('logs.view' if p == '/api/audit' else 'logs.activity')
            if p == '/api/activity':
                self.need_admin()  # what other people clicked is forensic data: administrators only
            node = qs.get('node', '') if is_admin(self.u) else ''
            return self.send(200, STORE.query_log('audit' if p == '/api/audit' else 'activity', qs.get('q', ''), qs.get('user', ''),
                                                  qs.get('type', ''), qs.get('scope', ''), qs.get('from', ''), qs.get('to', ''),
                                                  max(1, min(1000, int(qs.get('limit', 200)))), max(0, int(qs.get('offset', 0))), self.u['scopes'], node,
                                                  admin=is_admin(self.u)))
        if p == '/api/security':
            self.need('logs.security')
            self.need_admin()
            return self.send(200, AUTH.query_log(qs.get('q', ''), qs.get('user', ''), qs.get('type', ''), qs.get('from', ''), qs.get('to', ''),
                                                 max(1, min(1000, int(qs.get('limit', 200)))), max(0, int(qs.get('offset', 0))), qs.get('node', '')))
        if p == '/api/devices':
            self.need_admin()
            return self.send(200, SYNC.overview())
        if p == '/api/quick-links':
            self.need_admin()
            return self.send(200, {'users': AUTH.link_list(), 'authority': NODE.is_authority,
                                   'authorityHint': '' if NODE.is_authority else AUTH.authority_hint(), 'urls': lan_urls(CFG['port'])})
        if p == '/api/devices/log':
            self.need_admin()
            with JOURNAL.lock:
                rows = [dict(r) for r in JOURNAL.conn.execute('SELECT * FROM sync_log ORDER BY id DESC LIMIT ?', (min(1000, int(qs.get('limit', 300))),))]
            return self.send(200, rows)
        if p == '/api/conflicts':
            self.need_admin()
            return self.send(200, self.conflict_list())
        if p == '/api/users':
            self.need('users.manage')
            return self.send(200, {'users': AUTH.list_users(), 'permissions': PERMISSIONS, 'profiles': AUTH.profiles(), 'adminPerms': sorted(ADMIN_PERMS),
                                   'authority': NODE.is_authority,
                                   'authorityHint': '' if NODE.is_authority else AUTH.authority_hint()})
        if p == '/api/export.xlsx':
            self.need('report.full')
            if self.u['scopes'] is not None:
                raise Forbidden('The complete export contains all trip categories; you only have access to some of them.')
            data = xlsx.build(STORE.export_sheets(admin=is_admin(self.u) and self.can('logs.activity')))
            log.info('EXPORT full workbook by %s (%s)', self.user, self.ip)
            STORE.log_activity(self.user, self.ip, [{'type': 'export', 'action': 'Full Excel export', 'target': 'All data'}])
            return self.send(200, data, TYPES['.xlsx'], {'Content-Disposition': f'attachment; filename="TO_Full_Export_{datetime.now():%Y-%m-%d_%H%M}.xlsx"'})
        if p.startswith('/files/'):
            if os.path.splitext(p)[1].lower() not in IMAGE_EXT:
                self.need('files.download')
            return self.serve_file(UPLOADS, p[len('/files/'):], upload=True, src=p)
        self.send(404, {'error': 'Not found'})

    def _post(self):
        p = urlparse(self.path).path
        qs = {k: v[0] for k, v in parse_qs(urlparse(self.path).query).items()}
        origin = self.headers.get('Origin')
        if origin and urlparse(origin).netloc != self.headers.get('Host'):
            raise Forbidden('Request from another web site was blocked.')

        # ---------------- no login needed
        if p.startswith('/k/'):  # personal link: the page below sends this by itself
            if too_many_failures(self.ip):
                raise AuthError('Too many attempts. Wait a minute and try again.')
            try:
                token, u = AUTH.link_login(p[3:], self.ip, self.headers.get('User-Agent', ''))
            except AuthError:
                too_many_failures(self.ip, add=True)
                time.sleep(0.6)
                return self.link_page(p[3:])
            if self.token:
                AUTH.logout(self.token, None, self.ip)  # whoever was logged in in this browser before
            say(f'Login with personal link: {u["display"]} ({self.ip})')
            return self.send(303, b'', 'text/plain', {'Location': '/', **self.set_session(token)})
        if p == '/api/auth/login':
            d = self.json_body()
            if too_many_failures(self.ip):
                raise AuthError('Too many wrong attempts from this computer. Wait a minute and try again.')
            try:
                token, u = AUTH.login(d.get('username'), d.get('password'), self.ip, self.headers.get('User-Agent', ''))
            except AuthError:
                too_many_failures(self.ip, add=True)
                time.sleep(0.6)  # slows down password guessing
                raise
            self.u = u
            say(f'Login: {u["display"]} ({self.ip})')
            return self.send(200, self.me(), headers=self.set_session(token))
        if p == '/api/join':
            if self.ip not in LOCAL_IPS or AUTH.has_users() or NODE.role != 'unconfigured':
                raise Forbidden('Joining is only possible on a new, not yet set up PC, on the PC itself.')
            d = self.json_body()
            try:
                return self.send(200, SYNC.join(d.get('address'), d.get('code'), d.get('name')))
            except ValueError as e:
                raise BadRequest(str(e))
        if p == '/api/join/discover':
            if self.ip not in LOCAL_IPS or AUTH.has_users() or NODE.role != 'unconfigured':
                raise Forbidden('Only on a new, not yet set up PC, on the PC itself.')
            return self.send(200, {'found': SYNC.discover()})
        if p == '/api/join/cancel':
            if self.ip not in LOCAL_IPS or NODE.role != 'unconfigured':
                raise Forbidden('Not possible.')
            JOURNAL.set_meta('join', None)
            return self.send(200, {'ok': True})
        if p == '/api/node/moved':
            if self.ip not in LOCAL_IPS or not NODE.moved:
                raise Forbidden('Only on this PC itself.')
            choice = self.json_body().get('choice')
            if choice == 'same':
                NODE.confirm_same_machine()
                AUTH.log('This PC', self.ip, 'node-confirmed', NODE.name, 'Confirmed on this PC: same computer as before (name or network card changed)')
                SYNC.kick()
                return self.send(200, {'ok': True})
            if choice == 'new':
                with open(os.path.join(NODE.dir, 'RESET_REQUESTED'), 'w') as f:
                    f.write(now())
                return self.send(200, {'ok': True, 'restart': True})
            raise BadRequest('Choose same or new')
        if p == '/api/auth/setup':
            if self.ip not in LOCAL_IPS:
                raise Forbidden('The first administrator account can only be created on the PC with the program itself.')
            d = self.json_body()
            AUTH.setup(d.get('username'), d.get('full_name'), d.get('password'), self.ip)
            token, self.u = AUTH.login(d.get('username'), d.get('password'), self.ip, self.headers.get('User-Agent', ''))
            say(f'Administrator account created: {self.u["display"]}')
            return self.send(200, self.me(), headers=self.set_session(token))
        if p == '/api/auth/logout':
            u = AUTH.session(self.token, self.ip, touch=False)
            AUTH.logout(self.token, u, self.ip)
            return self.send(200, {'ok': True}, headers=self.clear_session())

        # ---------------- logged in
        self.login_required()
        if p == '/api/auth/password':
            d = self.json_body()
            AUTH.change_password(self.u, d.get('old'), d.get('new'), self.ip, self.token)
            self.u = AUTH.get(self.u['id'])
            return self.send(200, self.me())
        if p == '/api/log':
            d = self.json_body()
            events = [{**e, 'user': self.user} for e in (d.get('events') or []) if isinstance(e, dict)]  # never trust a name sent by the page
            STORE.log_activity(self.user, self.ip, events)
            return self.send(200, {'ok': True})
        if self.u['must_change']:
            raise Forbidden('Please change your temporary password first.')
        if NODE.moved:
            raise Forbidden('This PC needs a decision first: its data folder seems to come from another PC. Open the system on this PC itself.')
        if p == '/api/commit':
            d = self.json_body()
            label = str(d.get('label') or 'Change')[:200]
            force = bool(d.get('force'))
            if force:
                self.need('data.import')
                if STORE.counts().get('Trips'):
                    BACKUPS.create('pre-import')
            if any(isinstance(o, dict) and 'resolve' in o for o in (d.get('ops') or []) if isinstance(d.get('ops'), list)):
                raise Forbidden('Conflicts are decided only in Devices & Sync by an administrator.')
            res = STORE.commit(self.user, self.ip, label, tripsvc.normalize_ops(STORE, d.get('ops')), force, guard=commit_guard(self.u), user_id=self.u['id'])
            log.info('COMMIT %s (%s) "%s" %s changes', self.user, self.ip, label, res['changes'])
            return self.send(200, res)
        if p == '/api/word/preview':
            self.need('excel.import')
            self.need_all_scopes()
            try:
                pid, plan = word_io.preview(self.user, self.body(30 * 1048576), STORE.state(), qs.get('category', ''), qs.get('name', '')[:120])
                return self.send(200, {'id': pid, **plan})
            except (word_io.WordError, excel_io.ImportError_) as e:
                raise BadRequest(str(e))
        if p.startswith('/api/excel/'):
            action = p[len('/api/excel/'):]
            self.need('excel.import')
            self.need_all_scopes()
            try:
                if action == 'preview':
                    data = self.body(30 * 1048576)
                    pid, plan = excel_io.make_preview(self.user, data, STORE.state(), qs.get('name', '')[:120])
                    return self.send(200, {'id': pid, **plan})
                if action == 'commit':
                    d = self.json_body()
                    plan = excel_io.get_preview(str(d.get('id')), self.user)
                    ops, n = excel_io.build_ops(plan, STORE.state(), tripsvc.my_letter(JOURNAL, NODE.id), d.get('skip') or [], d.get('merges') or [],
                                                include_problems=bool(d.get('includeProblems')))
                    BACKUPS.create('pre-import')
                    res = STORE.commit(self.user, self.ip, f'{"Word" if plan.get("source") == "word" else "Excel"} import {plan.get("filename") or ""} ({n} trips)', ops, user_id=self.u['id'])
                    excel_io.drop_preview(str(d.get('id')))
                    STORE.log_activity(self.user, self.ip, [{'type': 'import', 'action': 'Excel import', 'target': plan.get('filename') or '', 'detail': f'{n} trips'}])
                    return self.send(200, {'trips': n, 'changes': res['changes']})
            except excel_io.ImportError_ as e:
                raise BadRequest(str(e))
            return self.send(404, {'error': 'Not found'})
        if p.startswith('/api/trips/'):
            d = self.json_body()
            action = p[len('/api/trips/'):]
            g = commit_guard(self.u)
            args = (STORE, self.user, self.ip, self.u['id'])
            if action == 'new':
                self.need('trips.create')
                return self.send(200, tripsvc.create_trip(STORE, JOURNAL, NODE.id, self.user, self.ip, self.u['id'], d, guard=g))
            if action == 'amend':
                self.need('trips.amend', 'trips.review')
                return self.send(200, tripsvc.amend(*args, str(d.get('id')), d.get('field'), d.get('value'), d.get('reason'), guard=g))
            if action == 'cancel':
                self.need('trips.cancel')
                return self.send(200, tripsvc.cancel(*args, str(d.get('id')), d.get('reason'), guard=g))
            if action == 'approve':
                self.need('trips.approve')
                return self.send(200, tripsvc.approve(*args, str(d.get('id')), bool(d.get('yes')), guard=g))
            return self.send(404, {'error': 'Not found'})
        if p == '/api/first-run':
            self.need('data.import')
            won = STORE.claim_first_run()
            if won:
                say(f'New database - sample data is being loaded by {self.user} ({self.ip})')
            return self.send(200, {'loadSample': won})
        if p == '/api/upload':
            self.need('settings.edit', 'data.import', 'trips.create')
            return self.upload(qs.get('name', 'file'))
        if p == '/api/xlsx':
            self.need(*REPORT_PERMS)
            d = self.json_body()
            data = xlsx.build([(s.get('name', 'Sheet'), s.get('head', []), s.get('rows', [])) for s in d.get('sheets', [])])
            name = ''.join(ch for ch in str(d.get('filename') or 'export') if ch.isalnum() or ch in ' _-.')[:80]
            return self.send(200, data, TYPES['.xlsx'], {'Content-Disposition': f'attachment; filename="{name}.xlsx"'})
        if p == '/api/backups':
            self.need('backups.manage')
            name = BACKUPS.create('manual')
            log.info('BACKUP manual by %s: %s', self.user, name)
            STORE.log_activity(self.user, self.ip, [{'type': 'backup', 'action': 'Backup created', 'target': name}])
            return self.send(200, {'name': name})
        if p == '/api/backups/folder':  # a second folder (USB drive, other disk) that gets a copy of every backup
            self.need('backups.manage')
            if not is_admin(self.u):
                raise Forbidden('Only an administrator can choose the backup folder.')
            if self.ip not in LOCAL_IPS:
                raise Forbidden('For safety, choose the backup folder on this PC itself.')
            folder = str(self.json_body().get('path') or '').strip().strip('"')
            set_backup_folder(folder)
            AUTH.log(self.u['display'], self.ip, 'backup-folder', folder or '-', 'Second backup folder set' if folder else 'Second backup folder removed')
            name = BACKUPS.create('manual') if folder else ''
            return self.send(200, {'ok': not BACKUPS.last_error, 'error': BACKUPS.last_error, 'name': name})
        if p == '/api/backups/restore':
            self.need('backups.restore')
            d = self.json_body()
            safety, res = BACKUPS.restore(d.get('name'), self.user, self.ip, self.u['id'])
            STORE.log_activity(self.user, self.ip, [{'type': 'restore', 'action': 'Restored backup', 'target': d.get('name'),
                                                      'detail': f'{res["changes"]} records brought back; safety backup before restore: {safety}'}])
            AUTH.log(self.user, self.ip, 'backup-restored', d.get('name'), f'{res["changes"]} records changed back; safety backup: {safety}')
            say(f'Backup {d.get("name")} restored by {self.user} ({self.ip}); {res["changes"]} records; previous data saved as {safety}')
            return self.send(200, {'ok': True, 'safety': safety, 'changes': res['changes']})
        if p == '/api/trash/restore':
            self.need('trash.restore')
            self.need_all_scopes()
            d = self.json_body()
            return self.send(200, STORE.restore_txn(self.user, self.ip, str(d.get('txn'))))
        if p == '/api/quick-links/set':
            self.need_admin()
            d = self.json_body()
            AUTH.link_set(self.u, self.ip, str(d.get('id')), bool(d.get('on')))
            return self.send(200, {'ok': True})
        if p.startswith('/api/devices/'):
            self.need_admin()
            d = self.json_body()
            action = p[len('/api/devices/'):]
            try:
                if action == 'export-key':  # the administrator key, protected by a passphrase, as a file for a USB stick
                    if self.ip not in LOCAL_IPS:
                        raise Forbidden('For safety, save the administrator key on the administrator PC itself.')
                    if not NODE.is_authority or NODE.info.get('backup'):
                        raise Forbidden('Only the administrator PC can save the administrator key.')
                    pw = str(d.get('passphrase') or '')
                    if len(pw) < 12:
                        raise BadRequest('The passphrase must have at least 12 characters.')
                    import nodectl
                    box = nodectl.seal(NODE.authority_seed, pw, {'cluster': NODE.info.get('cluster_id'), 'authority_pub': NODE.info.get('authority_pub'),
                                                                 'exported': now(), 'from': NODE.name})
                    JOURNAL.set_meta('key_saved', now())
                    AUTH.log(self.u['display'], self.ip, 'authority-exported', NODE.name, 'Administrator key saved as a file (passphrase protected)')
                    return self.send(200, box, headers={'Content-Disposition': 'attachment; filename="TO-administrator-key.json"'})
                if action == 'invite':
                    return self.send(200, SYNC.create_invite(self.user))
                if action == 'decide':
                    SYNC.decide(str(d.get('id')), bool(d.get('approve')), self.u)
                elif action == 'update':
                    SYNC.update_node(str(d.get('id')), self.u, name=d.get('name'), address=d.get('address'))
                elif action == 'revoke':
                    SYNC.update_node(str(d.get('id')), self.u, revoke=True)
                elif action == 'backup':
                    SYNC.set_backup(str(d.get('id')), self.u, bool(d.get('on')))
                elif action == 'sync-now':
                    for st in SYNC.status.values():
                        st['fails'] = 0
                    SYNC.kick()
                elif action == 'verify':
                    rep = JOURNAL.verify(all_signatures=bool(d.get('all')))
                    AUTH.log(self.user, self.ip, 'integrity-check', 'history', 'OK' if rep['ok'] else f'{rep["problemCount"]} problem(s)')
                    return self.send(200, rep)
                elif action == 'ack':
                    JOURNAL.ack_alert(str(d.get('key')))
                else:
                    return self.send(404, {'error': 'Not found'})
            except PermissionError as e:
                raise Forbidden(str(e))
            except ValueError as e:
                raise BadRequest(str(e))
            return self.send(200, {'ok': True})
        if p == '/api/conflicts/resolve':
            self.need_admin()
            return self.send(200, self.resolve_conflict(self.json_body()))
        if p in ('/api/profiles/save', '/api/profiles/delete'):
            self.need('users.manage')
            d = self.json_body()
            if p.endswith('save'):
                return self.send(200, AUTH.save_profile(self.u, self.ip, d))
            AUTH.delete_profile(self.u, self.ip, str(d.get('id') or ''))
            return self.send(200, {'ok': True})
        if p.startswith('/api/users/'):
            self.need('users.manage')
            d = self.json_body()
            action = p[len('/api/users/'):]
            if action == 'save':
                return self.send(200, AUTH.save_user(self.u, self.ip, d))
            uid = str(d.get('id') or '')
            if action == 'reset':
                AUTH.reset_password(self.u, self.ip, uid, d.get('password'))
            elif action == 'unlock':
                AUTH.unlock(self.u, self.ip, uid)
            elif action == 'logout':
                AUTH.force_logout(self.u, self.ip, uid)
            elif action == 'delete':
                AUTH.delete_user(self.u, self.ip, uid)
            else:
                return self.send(404, {'error': 'Not found'})
            return self.send(200, {'ok': True})
        self.send(404, {'error': 'Not found'})

    # ------------------------------------------------------------ conflicts
    def conflict_list(self):
        out = STORE.conflicts()
        who = {}
        for c in out:
            if c['kind'] == 'conflict':
                for fld, entries in c['detail'].items():
                    for e in entries:
                        k = (e['origin'], e['cseq'])
                        if k not in who:
                            who[k] = JOURNAL.describe(*k)
                        e['by'] = who[k]
            elif c['kind'] == 'deleted-edit':
                c['delete_by'] = JOURNAL.describe(*c['detail']['delete'])
                c['edits_by'] = [JOURNAL.describe(*x) for x in c['detail']['edits'][:10]]
        return out

    def resolve_conflict(self, d):
        """The administrator decides: one value for a field, keep a record deleted, or bring it back."""
        from store import ENTITIES
        entity, rid, action = d.get('entity'), str(d.get('id') or ''), d.get('action')
        if entity not in ENTITIES:
            raise BadRequest('Unknown record type')
        table = ENTITIES[entity][0]
        with STORE.lock:
            r = STORE.conn.execute(f'SELECT * FROM {table} WHERE id=?', (rid,)).fetchone()
        if not r:
            raise BadRequest('Record not found')
        row = STORE._row_js(entity, r)
        ver = row.pop('ver')
        if action == 'value':
            field = d.get('field')
            row[field] = d.get('value')
            op = {'e': entity, 'id': rid, 'op': 'put', 'row': row, 'ver': ver, 'resolve': [field]}
            label = f'Conflict resolved: {field}'
        elif action == 'keep-deleted':
            op = {'e': entity, 'id': rid, 'op': 'del', 'resolve': True}
            label = 'Conflict resolved: keep deleted'
        elif action == 'restore':
            op = {'e': entity, 'id': rid, 'op': 'put', 'row': row}
            label = 'Conflict resolved: record restored'
        else:
            raise BadRequest('Unknown action')
        res = STORE.commit(self.user, self.ip, label, [op], force=action != 'value', user_id=self.u['id'])
        AUTH.log(self.user, self.ip, 'conflict-resolved', f'{entity} {rid}', label)
        return res

    # ------------------------------------------------------------ files
    def upload(self, name):
        ext = os.path.splitext(name)[1].lower()
        if ext not in UPLOAD_EXT:
            raise BadRequest(f'File type {ext or "(none)"} is not allowed')
        data = self.body(int(CFG['max_upload_mb']) * 1048576)
        if not data:
            raise BadRequest('Empty file')
        # content-addressed: the name is the SHA-256 of the content, so the same file is stored once and every PC can check its copy
        sha = hashlib.sha256(data).hexdigest()
        os.makedirs(os.path.join(UPLOADS, 'cas'), exist_ok=True)
        path = os.path.join(UPLOADS, 'cas', sha + ext)
        if not os.path.exists(path):
            tmp = os.path.join(UPLOADS, 'cas', f'.{sha}.{uuid.uuid4().hex[:8]}.tmp')
            with open(tmp, 'wb') as f:
                f.write(data)
                f.flush()
                os.fsync(f.fileno())
            os.replace(tmp, path)
        src = f'/files/cas/{sha}{ext}'
        STORE.record_file(src, sha, len(data), mimetypes.guess_type(path)[0] or '', self.user, self.ip, self.u['id'])
        log.info('UPLOAD %s (%s) %s -> %s %d bytes', self.user, self.ip, name, src, len(data))
        self.send(200, {'src': src, 'size': len(data)})

    def serve_static(self, rel):
        """The program's own web pages: from inside TripOrders.exe when installed, else from the program folder.
        Only index.html and files inside css/, js/ and lib/ - never anything else of the program folder (data, keys)."""
        rel = unquote(rel).replace('\\', '/')
        parts = rel.split('/')
        ext = os.path.splitext(rel)[1].lower()
        if (any(x in ('', '.', '..') or ':' in x for x in parts) or ext not in STATIC_EXT
                or not (rel == 'index.html' or len(parts) > 1 and parts[0] in ('css', 'js', 'lib', 'fonts'))):
            return self.send(404, {'error': 'File not found'})
        if ASSETS is not None:
            data = ASSETS.get(rel)
        else:
            path = os.path.join(ROOT, *parts)
            data = None
            if os.path.isfile(path):
                with open(path, 'rb') as f:
                    data = f.read()
        if data is None:
            return self.send(404, {'error': 'File not found'})
        ctype = TYPES.get(ext) or mimetypes.guess_type(rel)[0] or 'application/octet-stream'
        return self.send(200, data, ctype, {'Cache-Control': 'no-cache'})

    def serve_file(self, base, rel, upload=False, src=None):
        base = os.path.realpath(base)
        path = os.path.realpath(os.path.join(base, unquote(rel)))
        if not path.startswith(base + os.sep) or not os.path.isfile(path):
            if upload and src and STORE.file_info(unquote(src)) and os.path.splitext(path)[1].lower() in IMAGE_EXT:
                # known file that has not been copied from another PC yet - never cached
                return self.send(200, PLACEHOLDER, 'image/svg+xml', {'Cache-Control': 'no-store'})
            if upload and src and STORE.file_info(unquote(src)):
                return self.send(404, {'error': 'This file is still being copied from another PC. Try again in a minute.'})
            return self.send(404, {'error': 'File not found'})
        ext = os.path.splitext(path)[1].lower()
        if upload and ext not in UPLOAD_EXT:
            return self.send(404, {'error': 'File not found'})
        ctype = TYPES.get(ext) or mimetypes.guess_type(path)[0] or 'application/octet-stream'
        headers = {'Cache-Control': 'public, max-age=31536000, immutable'} if upload else {'Cache-Control': 'no-cache'}
        if upload and ext not in INLINE_EXT:
            headers['Content-Disposition'] = 'attachment'
        with open(path, 'rb') as f:
            self.send(200, f.read(), ctype, headers)


class Server(ThreadingHTTPServer):
    allow_reuse_address = os.name != 'nt'  # Windows: reuse would let a second copy share the port silently; elsewhere it only skips TIME_WAIT
    daemon_threads = True


def main(background=False):
    port = int(CFG['port'])
    if not INSTANCE:
        print('The system is already running on this PC. Opening it in the browser.')
        if not background:
            webbrowser.open(f'http://localhost:{port}/')
        return
    try:
        httpd = Server((CFG['host'], port), Handler)
    except OSError:
        print(f'Port {port} is already in use - the system is probably already running. Opening it in the browser.')
        if not background:  # a second start (e.g. the desktop icon while it runs in the background) just opens it
            webbrowser.open(f'http://localhost:{port}/')
        return

    try:
        if STORE.counts().get('Trips'):
            BACKUPS.create('startup')
    except Exception as e:
        say('Startup backup failed: ' + str(e))
    BACKUPS.start()
    SYNC.start()

    print('=' * 64)
    print(' Trip Orders is running')
    print(f' This PC:        http://localhost:{port}/')
    for u in lan_urls(port):
        print(f' Other PCs:      {u}')
    print(f' This PC:        "{NODE.name}" ({NODE.role}, id {NODE.id}), sync port {SYNC.port}')
    print(f' Data folder:    {DATA_DIR}')
    print(f' Backups folder: {BACKUPS.dir}')
    if not AUTH.has_users():
        print(' FIRST START: open http://localhost:%d/ on THIS PC to create the' % port)
        print('              administrator account (not possible from other PCs).')
    print(f' Version {VERSION} - {COPYRIGHT}')
    print(' Keep this window open. Close it to stop the system.')
    print('=' * 64, flush=True)
    say('Server started')
    if CFG.get('open_browser', True) and not background:
        threading.Timer(0.8, lambda: webbrowser.open(f'http://localhost:{port}/')).start()
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        SYNC.shutdown()
        JOURNAL.flush_activity()
        say('Server stopped')


if __name__ == '__main__':
    main()
