"""Downloads the bundled fonts (all SIL Open Font License) from the npm package @fontsource and writes
fonts/*.woff2, fonts/LICENSES/*.txt and css/fonts.css. Needs Node/npm and internet, only run by developers:

    python tools/install_fonts.py

The program itself never loads fonts from the internet (the office must work offline)."""
import glob
import os
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# key -> (npm package, CSS family name, weights, subsets)
FAMILIES = {
    'plex-arabic': ('ibm-plex-sans-arabic', 'TO Plex Arabic', (400, 500, 600, 700), ('arabic', 'latin')),
    'plex': ('ibm-plex-sans', 'TO Plex', (400, 500, 600, 700), ('latin',)),
    'cairo': ('cairo', 'TO Cairo', (400, 500, 600, 700), ('arabic', 'latin')),
    'tajawal': ('tajawal', 'TO Tajawal', (400, 500, 700), ('arabic', 'latin')),
    'kufi': ('noto-kufi-arabic', 'TO Kufi', (400, 500, 600, 700), ('arabic', 'latin')),
}
RANGES = {
    'latin': 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
    'arabic': 'U+0600-06FF,U+0750-077F,U+0870-088E,U+0890-0891,U+0898-08E1,U+08E3-08FF,U+200C-200E,U+2010-2011,U+204F,U+2E41,U+FB50-FDFF,U+FE70-FE74,U+FE76-FEFC',
}


def main():
    tmp = tempfile.mkdtemp(prefix='to-fonts-')
    os.makedirs(os.path.join(ROOT, 'fonts', 'LICENSES'), exist_ok=True)
    css = ['/* Generated by tools/install_fonts.py - bundled fonts (SIL Open Font License, see fonts/LICENSES). Do not edit. */']
    for key, (pkg, family, weights, subsets) in FAMILIES.items():
        subprocess.run(['npm', 'pack', f'@fontsource/{pkg}', '--silent'], cwd=tmp, check=True, capture_output=True)
        tgz = glob.glob(os.path.join(tmp, f'fontsource-{pkg}-[0-9]*.tgz'))[0]
        out = os.path.join(tmp, key)
        os.makedirs(out)
        subprocess.run(['tar', 'xzf', tgz, '-C', out], check=True)
        files = os.path.join(out, 'package', 'files')
        shutil.copy(os.path.join(out, 'package', 'LICENSE'), os.path.join(ROOT, 'fonts', 'LICENSES', f'{key}.txt'))
        for sub in subsets:
            for w in weights:
                src = os.path.join(files, f'{pkg}-{sub}-{w}-normal.woff2')
                dst = f'{key}-{sub}-{w}.woff2'
                shutil.copy(src, os.path.join(ROOT, 'fonts', dst))
                css.append(f"@font-face{{font-family:'{family}';font-style:normal;font-display:swap;font-weight:{w};"
                           f"src:url(../fonts/{dst}) format('woff2');unicode-range:{RANGES[sub]}}}")
    with open(os.path.join(ROOT, 'css', 'fonts.css'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(css) + '\n')
    shutil.rmtree(tmp, ignore_errors=True)
    print('fonts installed:', len(glob.glob(os.path.join(ROOT, 'fonts', '*.woff2'))), 'files')


if __name__ == '__main__':
    sys.exit(main())
