"""Packs the web pages (index.html, css, js, lib, fonts) into one Python module, so the installed program carries them
inside TripOrders.exe instead of as open files.

    python tools/make_assets.py [output file]      (default: server/_assets.py, which git ignores)
"""
import os
import sys
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARTS = ['index.html', 'css', 'js', 'lib', 'fonts']


def collect():
    files = {}
    for part in PARTS:
        full = os.path.join(ROOT, part)
        if os.path.isfile(full):
            files[part] = full
            continue
        for base, _, names in os.walk(full):
            for n in sorted(names):
                p = os.path.join(base, n)
                files[os.path.relpath(p, ROOT).replace(os.sep, '/')] = p
    return files


def main(out):
    files = collect()
    lines = ['"""Generated by tools/make_assets.py - the web pages of the program. Do not edit."""', 'import zlib', '', '_Z = {']
    for rel, path in sorted(files.items()):
        with open(path, 'rb') as f:
            lines.append(f'    {rel!r}: {zlib.compress(f.read(), 9)!r},')
    lines += ['}', 'ASSETS = {k: zlib.decompress(v) for k, v in _Z.items()}', 'del _Z', '']
    with open(out, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f'{len(files)} files packed into {out}')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'server', '_assets.py'))
